"""QF13 / audit C4: a retried chat request must not write a second row.

docs/bot-output-quality-plan.md §11 phase 4. `client_message_id` was stored and
read back to attach feedback, but the INSERT had no ON CONFLICT, so it was a
column and not an idempotency key.

Structural only, by design. These assert the DDL and the statement are shaped
correctly; the semantic check (insert twice, get one row) happens when the
migration is applied dark against the control DB, per the `migration-apply-dark`
skill. A test that created a unique index would need a writable database, and the
only one configured here is production.
"""
import re
from pathlib import Path

import pytest

_ROOT = Path(__file__).resolve().parent.parent
_MIGRATION = _ROOT / "alembic_migrations" / "versions" / "0038_chat_logs_idempotency.py"


@pytest.fixture(scope="module")
def migration_sql():
    return _MIGRATION.read_text()


class TestMigrationShape:
    def test_the_migration_exists_and_follows_0037(self, migration_sql):
        assert "revision: str = '0038'" in migration_sql
        assert "down_revision: Union[str, Sequence[str], None] = '0037'" in migration_sql

    def test_it_is_idempotent(self, migration_sql):
        # Project rule: every migration must be safe to re-run.
        assert "CREATE UNIQUE INDEX IF NOT EXISTS" in migration_sql
        assert "DROP INDEX IF EXISTS" in migration_sql

    def test_the_key_is_scoped_to_the_tenant(self, migration_sql):
        # client_message_id is generated by the client, so two tenants can mint the
        # same value; a global unique would let one tenant suppress another's write.
        assert "(company_id, client_message_id)" in migration_sql

    def test_nulls_stay_unconstrained(self, migration_sql):
        # Older widgets send no id at all. Without the partial clause every legacy
        # row would collide with every other legacy row.
        assert "WHERE client_message_id IS NOT NULL" in migration_sql

    def test_it_does_not_use_concurrently(self, migration_sql):
        # Alembic runs inside a transaction, where CONCURRENTLY is rejected.
        # Matched against the DDL, not the prose - the docstring explains why it
        # is absent, and a bare substring check reads that as a violation.
        assert not re.search(r"INDEX\s+CONCURRENTLY", migration_sql, re.IGNORECASE)


class TestNoDuplicateMigrationNumber:
    def test_0038_is_claimed_exactly_once(self):
        versions = (_ROOT / "alembic_migrations" / "versions").glob("*.py")
        heads = [p for p in versions if p.name.startswith("0038")]
        assert len(heads) == 1, f"migration number collision: {[p.name for p in heads]}"


class TestInsertStatement:
    def test_the_chat_log_insert_is_idempotent(self):
        source = (_ROOT / "main.py").read_text()
        insert = re.search(r"INSERT INTO chat_logs \(company_id.*?\"\"\"", source, re.S)
        assert insert, "chat_logs INSERT not found - did the statement move?"
        assert "ON CONFLICT DO NOTHING" in insert.group(0)

    def test_the_conflict_target_is_untargeted(self):
        # Naming the index would make this statement fail outright on any
        # environment where the code deploys before the migration runs, taking
        # chat logging down rather than duplicating a row.
        source = (_ROOT / "main.py").read_text()
        assert "ON CONFLICT (company_id, client_message_id)" not in source

    def test_feedback_still_resolves_a_turn_by_client_message_id(self):
        # The column's original consumer must keep working.
        source = (_ROOT / "main.py").read_text()
        assert "client_message_id" in source
        assert source.count("client_message_id") >= 3
