"""chat_logs idempotency key on client_message_id (audit C4 / QF13).

Revision ID: 0038
Revises: 0037
Created: 2026-08-12 (bot-output-quality plan §11 phase 4).

  uq_chat_logs_client_message  UNIQUE (company_id, client_message_id)
                               WHERE client_message_id IS NOT NULL

`client_message_id` has been stored since the feedback work and is read back to
attach a thumbs-up/down to the right turn, but nothing ever enforced it: the
INSERT had no ON CONFLICT, so a retried request - a dropped SSE connection, a
double-tap on send, a proxy retry - wrote a second row for the same visitor
message. It was a column, not an idempotency key.

Scoped to `company_id`, not global: the id is generated by the client, so two
tenants can legitimately mint the same value and a global constraint would let one
tenant's write silently suppress another's. Partial on NOT NULL because older
widgets do not send the field at all, and NULLs must stay unconstrained rather
than collapsing every legacy row into one.

Verified before shipping: zero duplicate (company_id, client_message_id) groups in
production across 1,012 rows (284 carrying the id), so the index builds without a
cleanup step. Plain CREATE INDEX rather than CONCURRENTLY - the table is small and
Alembic runs inside a transaction, where CONCURRENTLY is not permitted.

Control-plane only, matching 0031 / 0034 / 0036 / 0037: BYOD tenant chat_logs go
through `tenant_log_chat`, which does not carry this column.

Idempotent (CREATE UNIQUE INDEX IF NOT EXISTS): safe to re-run, and a safe no-op +
stamp when it later runs via Alembic on deploy.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa: F401


revision: str = '0038'
down_revision: Union[str, Sequence[str], None] = '0037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

INDEX_NAME = "uq_chat_logs_client_message"


def upgrade() -> None:
    op.execute(
        f"""CREATE UNIQUE INDEX IF NOT EXISTS {INDEX_NAME}
            ON chat_logs (company_id, client_message_id)
            WHERE client_message_id IS NOT NULL"""
    )


def downgrade() -> None:
    op.execute(f"DROP INDEX IF EXISTS {INDEX_NAME}")
