"""
Schema audit — Step 4.1 of the production-readiness plan.

READ-ONLY introspection of the live Postgres schema. Outputs a markdown
report comparing the actual database against what migrations/v8-v22 SQL
files plus the startup_event ALTER TABLE block expect to exist.

Usage:
    cd Sapybase_ai_engine
    source venv/bin/activate
    export DATABASE_URL="<your prod URL>"   # already in .env
    python scripts/schema_audit.py > migrations/SCHEMA_AUDIT_$(date +%Y-%m-%d).md

Every SQL call below is a SELECT against information_schema or pg_catalog.
No DDL, no DML, nothing that could mutate state. Safe to run against prod.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Optional

import psycopg2
from dotenv import load_dotenv


# Load DATABASE_URL from .env (or .env.local) — same pattern as main.py.
ROOT = Path(__file__).resolve().parent.parent
for env_file in (".env.local", ".env"):
    p = ROOT / env_file
    if p.exists():
        load_dotenv(p)
        break

DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    print("ERROR: DATABASE_URL not set. Add it to .env or export it.", file=sys.stderr)
    sys.exit(1)


# ── Schema we EXPECT to exist, derived from the v8-v22 migration files
#    and the startup_event ALTER TABLE block in main.py. The audit
#    compares actual against this. Discrepancies = drift to investigate.
EXPECTED_TABLES = {
    "users": {
        "id", "clerk_id", "email", "tier", "subscription_status",
        "trial_end_date", "polar_customer_id", "billing_period_end",
        "custom_plan_config", "role", "status", "created_at",
        "last_polar_event_at",  # added in Step 2.2
    },
    "companies": {
        "id", "user_id", "company_name", "company_tone", "theme_color",
        "allowed_origin", "domain", "system_prompt", "bot_name", "logo_url",
        "initial_message", "quick_questions", "logo_shape", "custom_logo_url",
        "avatar_bg_style", "api_key", "is_active", "display_order", "created_at",
        # Added via startup_event self-healing block:
        "ai_model", "webhook_url", "handoff_redirect_url",
        # Added via earlier migrations:
        "hide_branding",
    },
    "company_knowledge": {
        "id", "company_id", "content", "url", "embedding",
        "chunk_type", "parent_id", "created_at",
    },
    "usage_tracking": {
        "id", "user_id", "company_id", "messages_used",
        "period_start", "period_end",
    },
    "exact_query_cache": {
        "id", "company_id", "query_hash", "response", "created_at",
    },
    "admin_audit_log": {
        "id", "admin_clerk_id", "action", "target_id", "changes", "created_at",
    },
    "processed_webhooks": {
        "webhook_id", "provider", "processed_at",
    },
    "eval_runs": {
        "id", "company_id", "run_label", "triggered_by",
        "total_questions", "avg_retrieval_score", "avg_faithfulness_score",
    },
    # Roughly — eval has companion tables. Will be detected if present.
}

EXPECTED_EXTENSIONS = {"pgvector", "vector", "uuid-ossp"}


def fetchall(conn, sql: str, params: Optional[tuple] = None) -> list:
    """SELECT-only helper. Asserts no DDL keywords."""
    forbidden = ("INSERT", "UPDATE", "DELETE", "ALTER", "DROP", "CREATE", "TRUNCATE")
    if any(k in sql.upper() for k in forbidden):
        raise RuntimeError(f"SAFETY VIOLATION: non-SELECT in fetchall: {sql[:80]}")
    cur = conn.cursor()
    cur.execute(sql, params or ())
    rows = cur.fetchall()
    cur.close()
    return rows


def main():
    print("# Schema Audit Report")
    print()
    print("**Generated by `scripts/schema_audit.py`. Read-only — no schema mutation.**")
    print()

    conn = psycopg2.connect(DATABASE_URL)
    conn.set_session(readonly=True)  # Belt + suspenders: refuse all writes at the session level

    try:
        # ── 1. Postgres version
        rows = fetchall(conn, "SELECT version()")
        print(f"- **Postgres version:** `{rows[0][0]}`")

        # ── 2. Database size
        rows = fetchall(conn, "SELECT pg_size_pretty(pg_database_size(current_database()))")
        print(f"- **DB size:** `{rows[0][0]}`")

        # ── 3. Extensions installed
        rows = fetchall(conn, "SELECT extname, extversion FROM pg_extension ORDER BY extname")
        print()
        print("## Extensions")
        print()
        actual_exts = {r[0] for r in rows}
        for name, version in rows:
            marker = "✅" if name in EXPECTED_EXTENSIONS or name == "plpgsql" else "❓"
            print(f"- {marker} `{name}` (v{version})")
        missing_exts = EXPECTED_EXTENSIONS - actual_exts - {"vector"}  # vector and pgvector are aliases
        if missing_exts and "vector" not in actual_exts and "pgvector" not in actual_exts:
            print()
            print("**MISSING EXTENSIONS:**")
            for ext in missing_exts:
                print(f"- ❌ `{ext}`")

        # ── 4. All tables in public schema
        rows = fetchall(
            conn,
            """
            SELECT table_name
            FROM information_schema.tables
            WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
            ORDER BY table_name
            """
        )
        actual_tables = {r[0] for r in rows}

        print()
        print("## Tables — Expected vs Actual")
        print()
        print("| Table | Status | Note |")
        print("|---|---|---|")
        for name in sorted(EXPECTED_TABLES.keys() | actual_tables):
            in_expected = name in EXPECTED_TABLES
            in_actual = name in actual_tables
            if in_expected and in_actual:
                status = "✅ present"
                note = ""
            elif in_expected and not in_actual:
                status = "❌ MISSING"
                note = "Expected from migration files but not in DB"
            else:
                status = "❓ extra"
                note = "In DB but not in expected list — drift or undocumented"
            print(f"| `{name}` | {status} | {note} |")

        # ── 5. Per-table column check for tables that exist
        print()
        print("## Column-level audit (tables present in both expected and actual)")
        print()
        for tname in sorted(EXPECTED_TABLES.keys()):
            if tname not in actual_tables:
                continue
            print(f"### `{tname}`")
            print()

            rows = fetchall(
                conn,
                """
                SELECT column_name, data_type, is_nullable, column_default
                FROM information_schema.columns
                WHERE table_schema = 'public' AND table_name = %s
                ORDER BY ordinal_position
                """,
                (tname,)
            )
            actual_cols = {r[0] for r in rows}
            expected_cols = EXPECTED_TABLES[tname]

            missing = expected_cols - actual_cols
            extra = actual_cols - expected_cols

            print("| Column | Type | Nullable | Default | Status |")
            print("|---|---|---|---|---|")
            for cname, dtype, is_null, default in rows:
                in_expected = cname in expected_cols
                marker = "✅" if in_expected else "❓ extra"
                default_str = (default or "").replace("|", "\\|")[:40]
                print(f"| `{cname}` | `{dtype}` | {is_null} | `{default_str}` | {marker} |")
            for cname in sorted(missing):
                print(f"| `{cname}` | — | — | — | ❌ MISSING |")
            print()

        # ── 6. Indexes (just count + names, for sanity)
        print("## Indexes (count per table)")
        print()
        rows = fetchall(
            conn,
            """
            SELECT t.relname AS table_name, COUNT(i.indexname) AS idx_count
            FROM pg_indexes i
            JOIN pg_class t ON t.relname = i.tablename
            WHERE i.schemaname = 'public'
            GROUP BY t.relname
            ORDER BY t.relname
            """
        )
        for tname, count in rows:
            print(f"- `{tname}`: {count} indexes")

        # ── 7. Approximate row counts (cheap — uses pg_class.reltuples, not COUNT(*))
        print()
        print("## Approximate row counts (from `pg_class.reltuples`, not exact)")
        print()
        rows = fetchall(
            conn,
            """
            SELECT relname, reltuples::bigint
            FROM pg_class
            WHERE relkind = 'r'
              AND relname IN (
                  SELECT table_name FROM information_schema.tables
                  WHERE table_schema = 'public'
              )
            ORDER BY relname
            """
        )
        for tname, count in rows:
            print(f"- `{tname}`: ~{count:,} rows")

        print()
        print("---")
        print()
        print("## Findings to investigate")
        print()
        print("1. Any table marked ❌ MISSING means a migration file claims it exists but the DB doesn't.")
        print("2. Any table marked ❓ extra is drift — applied via raw SQL or an ad-hoc change not captured in any migration file.")
        print("3. Any column marked ❌ MISSING means the same drift, at the column level.")
        print("4. Any column marked ❓ extra is the same — DB has it, expected list doesn't. Either update the expected list (script bug) or document the drift.")
        print()
        print("This baseline becomes the source of truth for `0001_baseline.py` in the Alembic adoption (Step 4.4).")

    finally:
        conn.close()


if __name__ == "__main__":
    main()
